import React, { useState, useEffect } from "react";
import Container from "../components/Bits/Container/Container";

function BlackBox() {
  const [quote, setQuote] = useState("");

  useEffect(() => {
    const quotes = [
      "Can a man whos warm understand one whos freezing?",

      "Theres more than one way of working. If its for human beings—make sure and do it properly. If its for the big man, just make it look good.",

      "Shukhov felt pleased with life as he went to sleep.  A lot of good things had happened that day.  He hadnt been thrown in the hole. The gang hadnt been dragged off to Sotsgorodok.  Hed swiped the extra gruel at dinnertime.  The foreman had got a good rate for the job.  Hed enjoyed working on the wall.  He hadnt been caught with the blade at the search point.  Hed earned a bit from Tsezar that evening.  Hed bought his tobacco.  And he hadnt taken sick, had got over it. The end of an unclouded day.  Almost a happy one. Just one of the 3,653 days of his sentence, from bell to bell. The extra three were for leap years. ",

      "She made no effort to get things round her… She didnt struggle and strain to buy things and then care for them more than life itself. She didnt go all out after fine clothes.  Clothes, that beautify what is ugly and evil. She was misunderstood and abandoned even by her husband. She had lost six children, but not her sociable ways. She was a stranger to her sisters and sisters-in-law, a ridiculous creature who stupidly worked for others without pay. She didnt accumulate property against the day she died. A dirty-white goat, a gammy-legged cat, some rubber plants… We had all lived side by side with her and never understood that she was that righteous one without whom, as the proverb says, no village can stand. Nor any city. Nor our whole land.",

      "Take, say, the horse—prancing with arched back, stomping with hooves, with its sprawling mane and lucid warm eye. Or, take the camel—that two-humped swan, that languid sage with a smirk of cognition on its round lips. Take, even, the homely donkey—with its patient fortitude and lively, caressive ears. And we chose?…—this most unsightly of the Earths creatures, on fast rubber paws, with dead, glassy eyes and a blunt, ribbed snout, with an iron box for a hump. It will never neigh of the joy of the steppe, of the smells of the pastures, of its love for the mare or the master. Incessantly it grates its iron and spits, spits its violet fetid fume. Well, as we are—such also is our means of locomotion.",

      "On the surface of swift-running water you cannot make out the reflections of objects near or distant. Even if it is not muddy, even if it is free of foam, reflections in the ceaselessly wavering ripples, the boisterously shifting race are deceptive, vague, incomprehensible. Only when, from stream to stream, the current has reached a placid estuary, or in still backwaters, or in small lakes with never a tremulous wave, can we see in the mirror-smooth surface the smallest leaf of a tree on the bank, every fiber of a fine-combed cloud, and the intense blue depths of the sky. So it is with you and me. If, try as we may, we never have been and never shall be able to see, to reflect the truth in all its eternal fresh-minted clarity, is it not because we are still in motion, still living?…",

      "We can make you toe the line if we have to.",

      "Thats where youre wrong, Citizen Minister! Bobynins bold eyes flashed with undisguised hatred. Ive got nothing, understand, nothing at all! You cant get at my wife and child; a bomb got to them first. My parents are dead. All I own in this world is a handkerchief. These overalls and the buttonless shirt underneath them (he bared his chest to show it) belong to the state. You took my freedom from me long ago, and you cant give it back because you have no freedom yourself. Im forty two years old, and youve slapped a twenty five year sentence on me, Ive been in hard labor camps, walked about with number patches on my clothes, and wearing handcuffs, and with dogs around me, and Ive been in a penal work brigade; so what else can you threaten me with?  What else can you take away from me?  My engineers job, perhaps?  That would be your loss, not mine.",

      "The great truth for Innokenty used to be that we are given only one life. Now, with the new feeling that had ripened in him, he became aware of another law: that we are given only one conscience, too. Macbeths self-justifications were feeble—and his conscience devoured him. Yes, even Iago was a little lamb too. The imagination and the spiritual strength of Shakespeares evildoers stopped short at a dozen corpses. Because they had no ideology. Ideology—that is what gives evildoing its long-sought justification and gives the evildoer the necessary steadfastness and determination…. Thanks to ideology, the twentieth century was fated to experience evildoing on a scale calculated in the millions. This cannot be denied, nor passed over, not suppressed. How, then, do we dare insist that evildoers to not exist? And who was it that destroyed these millions? Without evildoers there would have been no Archipelago.",

      "It was granted me to carry away from my prison years on my bent back, which nearly broke beneath its load, this essential experience: how a human being becomes evil and how good… Gradually it was disclosed to me that the line separating good and evil passes not through states, nor between classes, nor between political parties either—but right through every human heart—and through all human hearts. This line shifts. Inside us, it oscillates with the years. And even within hearts overwhelmed by evil, one small bridgehead of good is retained. And even in the best of all hearts, there remains… an unuprooted small corner of evil. ",

      "Its high time to remember that our first allegiance is to the human race. And the human race broke away from the animal world through thought and speech. It is natural that these should be free. And if they are shackled—we return to our animal state. Glasnost, forthright and total glasnost—this is the first prerequisite for the health of any society, including our own. Whoever does not desire glasnost for our country is indifferent to his fatherland and thinks of nothing but his personal gain. Whoever does not desire glasnost for his fatherland—does not wish to cleanse it from diseases, but, rather, to drive them inside, there to fester.",

      "One {kind of} artist imagines himself the creator of an autonomous spiritual world; he hoists upon his shoulders the act of creating this world and of populating it, together with the total responsibility for it. But he collapses under the load, for no mortal genius can bear up under it, just as, in general, the man who declares himself the center of existence is unable to create a balanced spiritual system… Another {kind of} artist recognizes above himself a higher power and joyfully works as a humble apprentice under Gods heaven, though graver and more demanding still is his responsibility for all he writes or paints—and for the souls which apprehend it. However, it was not he who created this world, nor does he control it; there can be no doubts about its foundations. It is merely given to the artist to sense more keenly than others the harmony of the world, the beauty and ugliness of mans role in it—and to vividly communicate this to mankind.",

      "We shall be told: What can literature do in the face of a remorseless assault of open violence? But let us not forget that violence does not and cannot exist by itself. It is invariably intertwined with the lie. They are linked in the most intimate, most organic and profound fashion. Violence cannot conceal itself behind anything except lies, and lies have nothing to maintain them save violence. Anyone who has once proclaimed violence as his method must inexorably choose the lie as his principle… Violence [does not] always and necessarily lunge straight for your throat; more often than not it demands of its subjects only that they pledge allegiance to lies, that they participate in falsehood. The simple act of an ordinary brave man is not to participate in lies, not to support false actions! His rule: Let that come into the world, let it even reign supreme—only not through me. But it is within the power of writers and artists to do much more: to defeat the lie! For in the struggle with lies art has always triumphed and shall always triumph! Visibly, irrefutably for all! Lies can prevail against much in this world, but never against art.",

      "After the Western ideal of unlimited freedom, after the Marxist concept of freedom as acceptance of the yoke of necessity—here is the true Christian definition of freedom. Freedom is self-restriction! Restriction of the self for the sake of others! Once understood and adopted, this principle diverts us—as individuals, in all forms of human association, societies, and nations—from outward to inward development, thereby giving us greater spiritual depth.",

      "In autumn 1953 it looked very much as though I had only a few months to live. In December the doctors—comrades in exile—confirmed that I had at most three weeks left. All that I had memorized in the camps ran the risk of extinction together with the head that held it. This was a dreadful moment in my life: to die on the threshold of freedom, to see all I had written, all that gave meaning to my life thus far, about to perish with me… I did not die, however. (With a hopelessly neglected and acutely malignant tumor, this was a divine miracle; I could see no other explanation. Since then, all the life that has been given back to me has not been mine in the full sense: it is built around a purpose.)",

      "A decline in courage may be the most striking feature that an outside observer notices in the West today. The Western world has lost its civic courage, both as a whole and separately, in each country, in each government, in each political party, and of course, in the United Nations. Such a decline in courage is particularly noticeable among the ruling and intellectual elites, causing an impression of a loss of courage by the entire society. There remain many courageous individuals, but they have no determining influence on public life.",

      "I have spent all my life under a Communist regime and I will tell you that a society without any objective legal scale is a terrible one indeed. But a society with no other scale but the legal one is also less than worthy of man. A society based on the letter of the law and never reaching anything higher fails to take advantage of the full range of human possibilities.",

      "And yet in early democracies, as in American democracy at the time of its birth, all individual human rights were granted on the ground that man is Gods creature. That is, freedom was given to the individual conditionally, in the assumption of his constant religious responsibility. Such was the heritage of the preceding one thousand years. Two hundred or even fifty years ago, it would have seemed quite impossible, in America, that an individual be granted boundless freedom with no purpose, simply for the satisfaction of his whims. Subsequently, however all such limitations were eroded everywhere in the West; a total emancipation occurred from the moral heritage of Christian centuries with their great reserves of mercy and sacrifice. State systems were becoming ever more materialistic. The West has finally achieved the rights of man, and even to excess, but mans sense of responsibility to God and society has grown dimmer and dimmer.",

      "More than half a century ago, while I was still a child, I recall hearing a number of older people offer the following explanation for the great disasters that had befallen Russia: Men have forgotten God; thats why all this has happened., Since then I have spent well-nigh fifty years working on the history of our Revolution; in the process I have read hundreds of books, collected hundreds of personal testimonies, and have already contributed eight volumes of my own toward the effort of clearing away the rubble left by that upheaval. But if I were asked today to formulate as concisely as possible the main cause of the ruinous Revolution that swallowed up some sixty million of our people, I could not put it more accurately than to repeat: Men have forgotten God; thats why all this has happened.",

      "War is not the vilest form of evil, not the most evil of evils. An unjust trial, for instance, that scalds the outraged heart, is viler. Or murder for gain, when the solitary murderer fully understands the implications of what he means to do and all that the victim will suffer at the moment of the crime. Or the ordeal at the hands of a torturer. When you can neither cry out nor fight back nor attempt to defend yourself. Or treachery on the part of someone you trusted. Or mistreatment of widows or orphans. All these things are spiritually dirtier and more terrible than war.",

      "Nothing is more difficult than drawing a middle line for social development. The loud mouth, the big fist, the bomb, the prison bars are of no help to you, as they are to those at the two extremes. Following the middle line demands the utmost self-control, the most inflexible courage, the most patient calculation, the most precise knowledge.",

      "That revolution brings out instincts of primordial barbarism, the sinister forces of envy, greed, and hatred—this even its contemporaries could see all too well. They paid a terrible enough price for the mass psychosis of the day, when merely moderate behavior, or even the perception of such, already appeared to be a crime. But the twentieth century has done especially much to tarnish the romantic luster of revolution which still prevailed in the eighteenth century. As half-centuries and centuries have passed, people have learned from their own misfortunes that revolutions demolish the organic structures of society, disrupt the natural flow of life, destroy the best elements of the population and give free rein to the worst; that a revolution never brings prosperity to a nation, but benefits only a few shameless opportunists, while to the country as a whole it heralds countless deaths, widespread impoverishment, and, in the gravest cases, a long-lasting degeneration of the people.",

      "No, all hope cannot be pinned on science, technology, or economic growth. The victory of technological civilization has also instilled in us a spiritual insecurity. Its gifts enrich, but enslave us as well. All is interests, we must not neglect our interests, all is a struggle for material things; but an inner voice tells us that we have lost something pure, elevated, and fragile. We have ceased to see the purpose.",

      "It is up to us to stop seeing Progress (which cannot be stopped by anyone or anything) as a stream of unlimited blessings, and to view it rather as a gift from on high, sent down for an extremely intricate trial of our free will.",

      "A complex balancing act thus arises before the West. While maintaining full respect for the entire precious pluralism of world cultures and for their search for distinct social solutions, the West cannot at the same time lose sight of its own values, its historically unique stability of civic life under the rule of law—a hard-won stability which grants independence and space to every private citizen.",

      "I have worked here for almost eighteen years. It has been the most productive period in my life. I have done all that I wanted to do. Today, I offer those of my books that have been translated well into English to the town library. Our children grew up and went to school here, alongside your children. For them, Vermont is home. Indeed, our whole family has felt at home among you. Exile is always difficult, and yet I could not imagine a better place to live, and wait, and wait for my return home, than Cavendish, Vermont.",

      "Here in Cavendish, and in the surrounding towns, I have observed the sensible and sure process of grassroots democracy, in which the local population solves most of its problems on its own, not waiting for the decisions of higher authorities. Unfortunately, we do not have this in Russia, and that is still our greatest shortcoming. ",

      "Our Father All-Merciful! Dont abandon your own long-suffering Russia In her present daze, In her woundedness, Impoverishment, And confusion of spirit. Lord Omnipotent! Dont let, dont let her be cut short, To no longer be. So many forthright hearts And so many talents You had lodged among Russians. Do not let them perish or sink into darkness Without having served in Your name. Out of the depths of Calamity Save your disordered people.",

      "There are probably many definitions of patriotism. Nevertheless, I will present here the definition that I repeated on many occasions at public meetings in different parts of the country, and which was always received with understanding: Patriotism is an integral and persistent feeling of love for ones homeland, with a willingness to make sacrifices for her, to share her troubles, but not to serve her unquestioningly, not to support her unjust claims, rather, to frankly assess her faults, her transgressions, and to repent for these.",

      "I speak here about a clean, loving, constructive Russian patriotism and not of a radical nationalist bent (only our type! or only our faith!); not of the elevation of ones nationality above our higher spiritual plank, above our humble stance before Heaven. Needless to say, let us not call Russian patriotism the school that prefers a small-minded alliance with our communist destroyers.",

      "The Bolsheviks, for their part, quickly put the Russian character in irons and redirected it to their own ends…I will recapitulate briefly. A paralyzing fear spread over the country, a fear not only of arrest but of any action of the leadership (given the total and utter worthlessness of anyones rights, and the inability to escape from arbitrary rule by relocating.) A network of informants saturated the population. Secrecy and distrust permeated the people, so much so that any overt activity was perceived as a provocation. How many denunciations there were against ones own close relatives! or against friends who had fallen under the sword! A total, deafening indifference toward those who perished all around. An overpowering plume of betrayal. It was unavoidable: If you want to survive, lie. Lie and pretend. In place of all the good that was dying away, ingratitude, cruelty, and a thoroughly rude self-centered ambition now rose and established themselves.",

      "Having traveled far and wide across Russia these past four years, having watched, having listened, I am willing to state, under oath if need be:  No, our Spirit yet lives!  In its core it is uncorrupted!  There, in the meeting halls—I didnt say it, people would tell me, would try to convince me: Just save the soul of the people!  The rest will save itself. Yes, the Spirit is capable of reversing the direction of even the most fatal process.  It can pull us back even from the brink.  Some will find this difficult to believe.  But those who in their lives have come to see the justness and might of a higher power above us—those will believe that, despite a crushing century for Russians, there is hope for us yet.  It has not been taken away.",

      "The Communist dictatorship cried out for a sure and immediate resistance. However I on multiple occasions also asked Western countries not to equate Soviet Communism with Russia itself and with Russian history. Alas, many camps in the West drew no such distinction. The policy of western powers toward Russia after the fall of the Soviet dictatorship changed little in terms of rigidity. That is deeply disappointing. But things went even worse in Russia itself. Before a national recovery could take place (in the 1990s), both morally and economically the forces of darkness quickly won the upper hand; the most unprincipled thieves enriched themselves through the unimpeded plundering of the nations property, anchoring societys cynicism and the moral harm already perpetrated. That was a great catastrophe for the whole of Russia.",
    ];

    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    setQuote(randomQuote);
  }, []);

  return (
    <Container>
      "{quote}"<span>-Aleksandr Solzhenitsyn</span>
    </Container>
  );
}

export default BlackBox;
